# config/routes.yaml

# Route pour rediriger toutes les URL vers Vue.js
app_vue:
    path: /{vueRouting}
    controller: App\Controller\AppController::index
    requirements:
        vueRouting: .*
api_login:
  path: /login
  controller: App\Controller\LoginController::login
  methods: POST
